apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /guestbook-ui
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: apresti12/go-web-app:1.0
          name: guestbook-ui
          ports:
            - containerPort: 8083
